// import Footer from './Footer';
import Overlay from './overlay';
import Modal from './modal';
import Nav from './nav';
import Scroll from './scroll';
import Search from './search';
import Slider from './slider';
import Sticky from './sticky';
import Utils from './utils';
import FixedDropdown from './fixed-dropdown';
import SlidePage from './slide-page';
import RecommendationsFilter from './recommendations-filter';
import TagFilter from './tag-filter';

// Footer.init();
Modal.init();
Nav.init();
Overlay.init();
Scroll.init();
Search.init();
Slider.init();
Sticky.init();
Utils.markdownLinksNewPage();
FixedDropdown.init();
SlidePage.init();
RecommendationsFilter.init();
TagFilter.init();
